name: Test build on pull request to develop

on:
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up build environment
      run: |
        npm config set scripts-prepend-node-path true
        npm install yarn
        yarn install
    - name: Build
      run: yarn build
      env:
        CI: true